
# Default settings are ok for now
# [serve]
# The address to serve on LAN.
# address = "127.0.0.1"
# The address to serve on WAN.
# address = "0.0.0.0"
# The port to serve on.
# port = 8080


# This is already handled by yew https://trunkrs.dev/assets/#tailwind
# [[hooks]]
# stage = "pre_build"
# command = "tailwindcss"
# command_arguments = ["-i", "input.css", "-o", "index.css"]
